import { API_ROUTES, MIN_ADMIN_PASSWORD_LENGTH, type ChangeAdminPasswordRequest } from '@inscript-carte/shared';
import { useState } from 'react';

import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { api } from '@/lib/api';
import { ERROR_MESSAGES } from '@/registrations/messages';

type FormProps = {
  /** First sign-in with a generated password: the wording explains why. */
  forced: boolean;
  onChanged: () => void;
  onSessionExpired: () => void;
  onCancel?: () => void;
};

function ChangePasswordForm({ forced, onChanged, onSessionExpired, onCancel }: FormProps) {
  const [currentPassword, setCurrentPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [confirmation, setConfirmation] = useState('');
  const [message, setMessage] = useState<string | null>(null);
  const [sending, setSending] = useState(false);

  async function submit(event: React.FormEvent) {
    event.preventDefault();
    if (!currentPassword)
      return setMessage(`Merci de taper ${forced ? 'le mot de passe reçu' : 'votre mot de passe actuel'}.`);
    if (newPassword.length < MIN_ADMIN_PASSWORD_LENGTH) return setMessage(ERROR_MESSAGES.password_too_short);
    if (newPassword !== confirmation) return setMessage('Les deux nouveaux mots de passe ne sont pas identiques.');
    if (newPassword === currentPassword) return setMessage('Le nouveau mot de passe doit être différent de l’ancien.');

    setSending(true);
    const result = await api(API_ROUTES.adminPassword, {
      method: 'PUT',
      body: { currentPassword, newPassword } satisfies ChangeAdminPasswordRequest,
    });
    setSending(false);
    if (result.ok) return onChanged();
    if (result.error === 'admin_sign_in_required') return onSessionExpired();
    setMessage(
      result.error === 'invalid_credentials'
        ? `${forced ? 'Le mot de passe reçu' : 'Le mot de passe actuel'} est incorrect.`
        : ERROR_MESSAGES[result.error],
    );
  }

  return (
    <form onSubmit={submit} className='grid gap-4' noValidate>
      <div className='grid gap-2'>
        <Label htmlFor='current-password'>{forced ? 'Mot de passe reçu' : 'Mot de passe actuel'}</Label>
        <Input
          id='current-password'
          type='password'
          value={currentPassword}
          onChange={(event) => setCurrentPassword(event.target.value)}
          autoComplete='current-password'
          autoFocus
        />
      </div>
      <div className='grid gap-2'>
        <Label htmlFor='new-password'>Nouveau mot de passe (au moins {MIN_ADMIN_PASSWORD_LENGTH} caractères)</Label>
        <Input
          id='new-password'
          type='password'
          value={newPassword}
          onChange={(event) => setNewPassword(event.target.value)}
          autoComplete='new-password'
        />
      </div>
      <div className='grid gap-2'>
        <Label htmlFor='confirm-password'>Nouveau mot de passe, encore une fois</Label>
        <Input
          id='confirm-password'
          type='password'
          value={confirmation}
          onChange={(event) => setConfirmation(event.target.value)}
          autoComplete='new-password'
        />
      </div>
      {message && (
        <p role='alert' className='rounded-md bg-amber-50 px-3 py-2 text-sm text-amber-900'>
          {message}
        </p>
      )}
      <div className='flex flex-wrap justify-end gap-2'>
        {onCancel && (
          <Button type='button' variant='outline' onClick={onCancel}>
            Annuler
          </Button>
        )}
        <Button type='submit' disabled={sending}>
          {sending ? 'Enregistrement…' : 'Enregistrer le mot de passe'}
        </Button>
      </div>
    </form>
  );
}

/** First sign-in with a password generated by another admin: nothing else is shown until it is replaced. */
export function ForcedPasswordChange({ onChanged, onSessionExpired }: Omit<FormProps, 'forced' | 'onCancel'>) {
  return (
    <main className='mx-auto grid w-full max-w-md gap-4 p-4 pt-10'>
      <h1 className='text-2xl font-semibold tracking-tight'>Choisissez votre mot de passe</h1>
      <p className='text-muted-foreground'>
        Vous vous êtes connecté avec le mot de passe donné par un autre responsable. Pour la sécurité du club,
        choisissez maintenant un mot de passe que vous seul connaissez.
      </p>
      <ChangePasswordForm forced onChanged={onChanged} onSessionExpired={onSessionExpired} />
    </main>
  );
}

/** "Mot de passe" in the header. */
export function ChangePasswordDialog({
  onClose,
  onSessionExpired,
}: {
  onClose: () => void;
  onSessionExpired: () => void;
}) {
  const [done, setDone] = useState(false);
  return (
    <Dialog open onOpenChange={(open) => !open && onClose()}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Changer mon mot de passe</DialogTitle>
          <DialogDescription>Le mot de passe de l'espace administration, pas celui de la licence.</DialogDescription>
        </DialogHeader>
        {done ? (
          <>
            <p role='status' className='rounded-md bg-green-50 px-3 py-2 text-sm text-green-900'>
              Mot de passe changé.
            </p>
            <DialogFooter>
              <Button onClick={onClose}>Fermer</Button>
            </DialogFooter>
          </>
        ) : (
          <ChangePasswordForm
            forced={false}
            onChanged={() => setDone(true)}
            onSessionExpired={onSessionExpired}
            onCancel={onClose}
          />
        )}
      </DialogContent>
    </Dialog>
  );
}
