export type AdminAccount = {
  readonly passwordHash: string;
  /** The password was generated by another admin: the admin must replace it before using the panel. */
  readonly mustChangePassword: boolean;
};

/** Admins are club members with a personal password. */
export interface AdminRepository {
  /** `null` when this member is not an admin. */
  find(archerLicenceNumber: string): Promise<AdminAccount | null>;
  licenceNumbers(): Promise<string[]>;
  /** Makes the member an admin, or changes their password. */
  save(archerLicenceNumber: string, account: AdminAccount): Promise<void>;
  /** Also ends their admin sessions. `false` when the member was not an admin. */
  remove(archerLicenceNumber: string): Promise<boolean>;
}
